service: nestjs-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${env:NODE_ENV}
    PORT: ${env:PORT}
    STATUS: ${env:STATUS}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
